### ISSUE TITLE
IPLD Block Explorer cleanup

### ISSUE THREAD

**Issue by stellarmagnet** [vulcanize/ipld-block-explorer#19]

**Comment by ramilexe** [comment]
PR: https://github.com/vulcanize/ipld-block-explorer/pull/20

**Comment by ramilexe** [comment]
PR: https://github.com/vulcanize/ipld-block-explorer/pull/20

Next steps:
* merge
* create release `v0.2.0`
* bump version in block-explorer-demo: https://github.com/vulcanize/ipld-block-explorer-demo/blob/master/docker-compose.yml#L92
* ask @srwadleigh to deploy
