### ISSUE TITLE
Hide search bar

### ISSUE THREAD

**Issue by stellarmagnet** [vulcanize/ipld-block-explorer#22]

**Comment by AFDudley** [comment]
Shouldn't we just fix the search bar instead of hiding it?

**Comment by ramilexe** [comment]
> Shouldn't we just fix the search bar instead of hiding it?

search in this project implemented on a backend, so it requires refitting this logic and moving to frontend. Not 10 min work

**Comment by ramilexe** [comment]
Implemented hinding search bar in PR https://github.com/vulcanize/ipld-block-explorer/pull/20

**Comment by AFDudley** [comment]
Thanks for addressing this.
