### ISSUE TITLE
Transaction details - Add missing data and fix incorrect data

### ISSUE THREAD

**Issue by stellarmagnet** [vulcanize/ipld-block-explorer#24]
- [x] Block # field is missing - Include a field for the Block # that the transaction originates from, which should hyperlink to the Block details page

* [x] Timestamp field is missing
* [x] The Status is not populating properly (we know when it is successful - so it should properly display that it was successful, instead of it being a blank field)
* [x] Gas limit is incorrect
* [x] Gas used is incorrect

test:
https://rinkeby.etherscan.io/tx/0xca4232da2dd0cf71aae6d7923bffc77344bc8422197f8c72b74a5650e01d739b

https://explorer.vdb.to/tx/0xca4232da2dd0cf71aae6d7923bffc77344bc8422197f8c72b74a5650e01d739b

**Comment by ramilexe** [comment]
Fixed in https://github.com/vulcanize/ipld-block-explorer/pull/35
![image](https://user-images.githubusercontent.com/1008882/122221438-f2a36c00-ceb9-11eb-99d0-ac1bb729e727.png)
![image](https://user-images.githubusercontent.com/1008882/122221468-f8994d00-ceb9-11eb-9e49-b586c6b55198.png)

**Comment by stellarmagnet** [comment]
Closing this issue - although some new bugs were discovered and captured in the new ticket here:
https://github.com/vulcanize/ipld-block-explorer/issues/45
