### ISSUE TITLE
Metadata in Slack showing up incorrectly

### ISSUE THREAD

**Issue by stellarmagnet** [vulcanize/ipld-block-explorer#39]
Can we make updates to the metadata so it doesn't show up as EthVM in Slack or social media

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/13fb0821-16cc-4a57-8def-190fa6198881)

**Comment by ramilexe** [comment]
https://github.com/vulcanize/ipld-block-explorer/blob/main/newclient/public/index.html

**Comment by ramilexe** [comment]
https://github.com/vulcanize/ipld-block-explorer/blob/main/newclient/public/logo.png
